id: I4C8E34EC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:37:10+00:00'
last_modified: '2022-06-07T22:23:06.272802+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ46031
  title: མ་ཎི་བཀའ་འབུམ་ཆེན་མོ། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CE5E:
      image_group_id: I4CZ46033
      title: ''
      total_pages: 774
      order: 1
      base_file: CE5E.txt
    91A1:
      image_group_id: I4CZ46034
      title: ''
      total_pages: 658
      order: 2
      base_file: 91A1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
